#Data used by activity_tag_filters

filter = \
    {
        'countries': {
            'summer_vacation': {
                "AL": "Albania",
                "DZ": "Algeria",
                "AR": "Argentina",
                "AU": "Australia",
                "BS": "Bahamas",
                "BH": "Bahrain",
                "BD": "Bangladesh",
                "BB": "Barbados",
                "BZ": "Belize",
                "BM": "Bermuda",
                "BR": "Brazil",
                "BG": "Bulgaria",
                "KH": "Cambodia",
                "CL": "Chile",
                "CN": "China",
                "CO": "Colombia",
                "CR": "Costa Rica",
                "HR": "Croatia",
                "CU": "Cuba",
                "CY": "Cyprus",
                "DO": "Dominican Republic",
                "EG": "Egypt",
                "SV": "El Salvador",
                "FR": "France",
                "GR": "Greece",
                "GD": "Grenada",
                "GT": "Guatemala",
                "HN": "Honduras",
                "IN": "India",
                "ID": "Indonesia",
                "IT": "Italy",
                "JM": "Jamaica",
                "JP": "Japan",
                "JO": "Jordan",
                "KE": "Kenya",
                "KR": "South Korea",
                "KW": "Kuwait",
                "LB": "Lebanon",
                "LT": "Lithuania",
                "MY": "Malaysia",
                "MV": "Maldives",
                "MT": "Malta",
                "MX": "Mexico",
                "MA": "Morocco",
                "ME": "Montenegro",
                "NZ": "New Zealand",
                "NI": "Nicaragua",
                "OM": "Oman",
                "PA": "Panama",
                "PE": "Peru",
                "PH": "Philippines",
                "PT": "Portugal",
                "QA": "Qatar",
                "SA": "Saudi Arabia",
                "SG": "Singapore",
                "SI": "Slovenia",
                "ZA": "South Africa",
                "ES": "Spain",
                "LK": "Sri Lanka",
                "TH": "Thailand",
                "TN": "Tunisia",
                "TR": "Turkey",
                "AE": "United Arab Emirates",
                "US": "United States",
                "UY": "Uruguay",
                "VE": "Venezuela",
                "VN": "Vietnam"
    },
            'hiking' : {
                "AL": "Albania",
                "AD": "Andorra",
                "AM": "Armenia",
                "AT": "Austria",
                "AZ": "Azerbaijan",
                "BY": "Belarus",
                "BE": "Belgium",
                "BA": "Bosnia and Herzegovina",
                "BG": "Bulgaria",
                "HR": "Croatia",
                "CY": "Cyprus",
                "CZ": "Czech Republic",
                "DK": "Denmark",
                "EE": "Estonia",
                "FI": "Finland",
                "FR": "France",
                "GE": "Georgia",
                "DE": "Germany",
                "GR": "Greece",
                "HU": "Hungary",
                "IS": "Iceland",
                "IE": "Ireland",
                "IT": "Italy",
                "KZ": "Kazakhstan",
                "LV": "Latvia",
                "LI": "Liechtenstein",
                "LT": "Lithuania",
                "LU": "Luxembourg",
                "MT": "Malta",
                "MD": "Moldova",
                "MC": "Monaco",
                "ME": "Montenegro",
                "NL": "Netherlands",
                "MK": "North Macedonia",
                "NO": "Norway",
                "PL": "Poland",
                "PT": "Portugal",
                "RO": "Romania",
                "RU": "Russia",
                "SM": "San Marino",
                "RS": "Serbia",
                "SK": "Slovakia",
                "SI": "Slovenia",
                "ES": "Spain",
                "SE": "Sweden",
                "CH": "Switzerland",
                "TR": "Turkey",
                "UA": "Ukraine",
                "GB": "United Kingdom",
                "VA": "Vatican City"
    },
            'test_countries': {
                "AT": "Austria",
                "FR": "France",
                "IT": "Italy"
            },

    },
        'population':{
            'summer_vacation':{
                'min_population': 500,
                'max_population': 30000
            },
            'hiking':{
                'min_population': 500000,
                'max_population': 50000000
            },
            'test_population': {
                'min_population': 500,
                'max_population': 500000
            },
    },
        'geo_area':{
            'summer_vacation': [(-90,90,-180,180),],           #all surface on the planet
            'hiking':[(-90,90,-180,180),],
            'test_geo_area':[(-90,90,-180,180),],
        },
        'geo_area_exclude':{
            'summer_vacation': [(38,90,-25,68),],           #nothng to exclude
            'hiking':[(0,0,0,0),],
            'test_geo_area':[(0,0,0,0),],
        }
        }






