budget_cutoff = {'Budget': 0.33,
                 'Standard': 0.5,
                 'Lux': 1}


def hotel_weights(picked_budget, days_to_stay, activity_tag=None):
    if picked_budget == 'Budget':                                       #and days_to_stay > 5
        hotel_w = {'distances': 5,
                   'price_with_all_taxes': 10,
                   'is_meal': 3,
                   'free_cancellation_parameter': 1,
                   'star_rating': 1,
                   'rooms_number': 0,
                   'latitude': 0,
                   'longitude': 0,
                   'no_of_images': 3,
                   'total_rating': 2,
                   'cleanness_rating': 0,
                   'room_rating': 0,
                   'services_rating': 0,
                   'meal_rating': 2,
                   'hygiene_rating': 0,
                   'wifi_rating': 0,
                   'price_rating': 0,
                   'location_rating': 0,
                   'Washing machine': 0,
                   'Dishwasher': 0,
                   'Fridge': 0,
                   'TV': 0,
                   'Hairdryer': 0,
                   'Iron and board': 0,
                   'Coffee/tea for guests': 0,
                   'Kitchen': 0,
                   'Microwave oven': 0,
                   'Free Wi-Fi': 0,
                   'Internet access': 0,
                   'Air conditioning': 0,
                   'Heating': 0,
                   'Garden': 0,
                   'Terrace': 0,
                   'Indoor Fireplace': 0,
                   'Shower/Bathtub': 0,
                   'Shower': 0,
                   'Barbecue grill(s)': 0,
                   'Parking': 0,
                   'Parking nearby': 0,
                   'Swimming pool': 0,
                   'Outdoor pool': 0,
                   'Pets allowed': 0,
                   'Elevator/lift': 0,
                   'Smoke-free property': 0,
                   'All Spaces Non-Smoking (public and private)': 0,
                   'Upper floors accessible by elevator': 0,
                   'Non-smoking rooms': 0,
                   'Interconnecting rooms available': 0,
                   'Family room': 0,
                   'Cable TV': 0,
                   'Flat-screen TV': 0,
                   'Wardrobe/Closet': 0,
                   'Linens': 0,
                   'Toiletries': 0,
                   'Ironing': 0,
                   'Laundry': 0,
                   'Dry-cleaning': 0,
                   'Coffeemaker': 0,
                   'Airport transportation': 0,
                   'Spanish': 0,
                   'English': 0,
                   'Italian': 0,
                   'French': 0,
                   'Garage': 0,
                   'Beach/pool towels': 0,
                   'Family/Kid Friendly': 0,
                   "Kids' TV Networks": 0,
                   'Pets Not Allowed': 0,
                   'Outdoor furniture': 0,
                   'Multi-language staff': 0,
                   'Free parking': 0,
                   'Fitness facilities': 0,
                   'Extra decontamination measures': 0,
                   'Contactless check-in and/or check-out': 0,
                   'Additional measures against COVID-19': 0,
                   'Reception desk': 0,
                   'Slippers': 0,
                   'Telephone': 0,
                   'Restaurant': 0,
                   'Kettle': 0,
                   'Safe-deposit box': 0,
                   'Luggage storage': 0,
                   'Transfer services': 0,
                   'Smoke Detector': 0,
                   'Kitchenette': 0,
                   'Bathtub': 0,
                   'Common kitchen': 0,
                   'Chinese': 0,
                   'Conference Hall': 0,
                   'Picnic area': 0,
                   'Barbeque': 0,
                   'Hairdryer (on request)': 0,
                   'Wi-Fi': 0,
                   'Bar': 0,
                   'Spa tub': 0,
                   'In-room internet': 0,
                   'Carbon Monoxide Detector': 0,
                   'Room service': 0,
                   'Internet': 0,
                   'Smoking areas': 0,
                   '24-hour reception': 0,
                   'Currency exchange': 0,
                   'Bridal suite': 0,
                   'Accessibility features': 0,
                   'Concierge services': 0,
                   'Breakfast': 0,
                   'Breakfast in the room': 0,
                   'Snack bar': 0,
                   'Packed Lunches': 0,
                   'Bottled water (at extra charge)': 0,
                   'Car rental': 0,
                   'German': 0,
                   'Portuguese': 0,
                   'Tour assistance': 0,
                   'Library': 0,
                   'Fishing': 0,
                   'Sun Deck': 0,
                   'Free Parking on Premises': 0,
                   'Beach facilities': 0,
                   'Water sport facilities': 0,
                   'Fax and copy machine': 0,
                   'Windsurfing': 0,
                   'Yoga': 0,
                   'Massage': 0,
                   'Babysitting and childcare': 0,
                   'Express check-in/check-out': 0,
                   'Early check-in': 0,
                   'Late check-out': 0,
                   'Private check-in/check-out': 0,
                   'Dryer': 0,
                   'Soundproof rooms': 0,
                   'VIP room amenities': 0,
                   'Bathrobe': 0,
                   'Mosquito net': 0,
                   'Iron': 0,
                   'Free internet': 0,
                   'Russian': 0,
                   "Children's playground": 0,
                   'Temperature control for staff': 0,
                   'Personal protection equipment for staff': 0,
                   'Personal protection equipment for guests': 0,
                   'Next to the beach': 0,
                   'Fire Extinguisher': 0,
                   'No elevators': 0,
                   'Children swimming pool': 0,
                   'Hiking': 0,
                   'Security guard': 0,
                   'Wheelchair Accessible': 0,
                   'First Aid Kit': 0,
                   'Tennis court': 0,
                   'Spa': 0,
                   'Cycling': 0,
                   'Express check-in': 0,
                   'Gift shop': 0,
                   'Locker': 0,
                   'Restaurant (buffet style)': 0,
                   'Bottled water': 0,
                   'Billiards': 0,
                   'Ping-Pong': 0,
                   'Business center': 0,
                   'Event facilities': 0,
                   'Playroom': 0,
                   'Offsite parking reservations required': 0,
                   'ATM': 0,
                   'Airport transportation - drop-off': 0,
                   'Doctor': 0,
                   'Sauna': 0,
                   'Water park': 0,
                   'Newspapers': 0,
                   'Minibar': 0,
                   'Safe (in room)': 0,
                   'Cafe': 0,
                   'Temperature control for guests': 0,
                   'Ticket assistance': 0,
                   'Radio': 0,
                   'Smoking Allowed': 0,
                   'Wake-up service': 0,
                   'Airport transportation - pickup': 0,
                   'No parking': 0,
                   'Gym': 0,
                   'Allergy-free rooms': 0,
                   'Vending machine': 0,
                   'Meeting and presentation facilities': 0,
                   'Shopping on site': 0,
                   'Television in lobby': 0,
                   'Shuttle': 0,
                   'Suitable for Events': 0,
                   'Skiing': 0,
                   'Clothes rack': 0,
                   'Diving': 0,
                   'Indoor Pool': 0,
                   'Mini golf': 0,
                   'Free parking nearby': 0,
                   'Seasonal outdoor swimming pool': 0,
                   'Pool facilities': 0,
                   'Baby sleepers': 0,
                   'Diet menu (on request)': 0,
                   'Photocopy machines': 0,
                   'Korean': 0,
                   'Bike rental': 0,
                   'DVD Player': 0,
                   'Entertainment': 0,
                   'Darts': 0,
                   'Table Tennis': 0,
                   'Breakfast/lunch to go': 0,
                   'Individually packaged food': 0,
                   'Taxi booking': 0,
                   'Arabic': 0,
                   'Wi-Fi in the hotel': 0,
                   'Beauty services': 0,
                   'Solarium': 0,
                   'Bowling': 0,
                   'Casino': 0,
                   'Karaoke': 0,
                   'Nightclub': 0,
                   'Hunt': 0,
                   'Museum': 0,
                   'Water fun': 0,
                   'Badminton': 0,
                   'Horse riding': 0,
                   'Squash': 0,
                   'Boating': 0,
                   'Sailing': 0,
                   'Snorkelling': 0,
                   'Golf course': 0,
                   'Yachting': 0,
                   'Wheelchair access to restaurant': 0,
                   'Adults Only': 0,
                   'Design hotel': 0,
                   'Ski storage': 0,
                   'Ski-to-Door Access': 0,
                   'Ski shuttle': 0,
                   'Ironing accessories (by request)': 0,
                   'Patio': 0,
                   'Shoe shine': 0,
                   'Hammam': 0,
                   'Heated swimming pool': 0,
                   'Baths': 0,
                   'Health club': 0,
                   'Steam room': 0,
                   "Children's menu": 0,
                   'Computer': 0,
                   'Full board rates available': 0,
                   'Free train station shuttle': 0,
                   'Turkish': 0,
                   'Trouser press': 0,
                   'Private beach': 0,
                   'Pets allowed (free)': 0,
                   'Electric car charging': 0,
                   'Express check-out': 0,
                   'Alarm clock': 0,
                   'Chapel': 0,
                   'Polish': 0,
                   'Airport transportation (complimentary)': 0,
                   'Laptop safe': 0,
                   'Buffet breakfast': 0,
                   'Area shuttle': 0,
                   'Japanese': 0,
                   'Free bicycle rental': 0,
                   'Golf сourse (within 3 km)': 0,
                   'Shopping center shuttle': 0,
                   'Pharmacy': 0,
                   'Deposit boxes': 0,
                   'Beach shuttle': 0,
                   'Poolside bar': 0,
                   'Outdoor heated swimming pool': 0,
                   'Fax machine': 0,
                   'Rooftop pool': 0,
                   'Pets allowed (under 5 kg)': 0,
                   'Ice skating': 0,
                   'Kids club': 0,
                   'Winery': 0,
                   'Transfer to the beach': 0,
                   'Smoking allowed in bedrooms': 0,
                   'Mini-fridge': 0,
                   'Ski passes available': 0,
                   'Doorman': 0,
                   'Doctor on call': 0,
                   'Pets allowed (under 5 kg) (surcharge)': 0,
                   'Snowmobile and quad bikes rental': 0,
                   'Ski facilities rental': 0,
                   'Snowboard': 0,
                   'Skiing Off-site': 0,
                   'Music system': 0,
                   'Free shuttle': 0,
                   'Wheelchair access to bar': 0,
                   'Rental video equipment and computers': 0}
    elif picked_budget == 'Standard':                                   #and days_to_stay < 5:
        hotel_w = {'distances': 5,
                   'price_with_all_taxes': 10,
                   'is_meal': 3,
                   'free_cancellation_parameter': 0,
                   'star_rating': 0,
                   'rooms_number': 0,
                   'latitude': 0,
                   'longitude': 0,
                   'no_of_images': 0,
                   'total_rating': 0,
                   'cleanness_rating': 0,
                   'room_rating': 0,
                   'services_rating': 0,
                   'meal_rating': 0,
                   'hygiene_rating': 0,
                   'wifi_rating': 0,
                   'price_rating': 0,
                   'location_rating': 0,
                   'Washing machine': 0,
                   'Dishwasher': 0,
                   'Fridge': 0,
                   'TV': 0,
                   'Hairdryer': 0,
                   'Iron and board': 0,
                   'Coffee/tea for guests': 0,
                   'Kitchen': 0,
                   'Microwave oven': 0,
                   'Free Wi-Fi': 0,
                   'Internet access': 0,
                   'Air conditioning': 0,
                   'Heating': 0,
                   'Garden': 0,
                   'Terrace': 0,
                   'Indoor Fireplace': 0,
                   'Shower/Bathtub': 0,
                   'Shower': 0,
                   'Barbecue grill(s)': 0,
                   'Parking': 0,
                   'Parking nearby': 0,
                   'Swimming pool': 0,
                   'Outdoor pool': 0,
                   'Pets allowed': 0,
                   'Elevator/lift': 0,
                   'Smoke-free property': 0,
                   'All Spaces Non-Smoking (public and private)': 0,
                   'Upper floors accessible by elevator': 0,
                   'Non-smoking rooms': 0,
                   'Interconnecting rooms available': 0,
                   'Family room': 0,
                   'Cable TV': 0,
                   'Flat-screen TV': 0,
                   'Wardrobe/Closet': 0,
                   'Linens': 0,
                   'Toiletries': 0,
                   'Ironing': 0,
                   'Laundry': 0,
                   'Dry-cleaning': 0,
                   'Coffeemaker': 0,
                   'Airport transportation': 0,
                   'Spanish': 0,
                   'English': 0,
                   'Italian': 0,
                   'French': 0,
                   'Garage': 0,
                   'Beach/pool towels': 0,
                   'Family/Kid Friendly': 0,
                   "Kids' TV Networks": 0,
                   'Pets Not Allowed': 0,
                   'Outdoor furniture': 0,
                   'Multi-language staff': 0,
                   'Free parking': 0,
                   'Fitness facilities': 0,
                   'Extra decontamination measures': 0,
                   'Contactless check-in and/or check-out': 0,
                   'Additional measures against COVID-19': 0,
                   'Reception desk': 0,
                   'Slippers': 0,
                   'Telephone': 0,
                   'Restaurant': 0,
                   'Kettle': 0,
                   'Safe-deposit box': 0,
                   'Luggage storage': 0,
                   'Transfer services': 0,
                   'Smoke Detector': 0,
                   'Kitchenette': 0,
                   'Bathtub': 0,
                   'Common kitchen': 0,
                   'Chinese': 0,
                   'Conference Hall': 0,
                   'Picnic area': 0,
                   'Barbeque': 0,
                   'Hairdryer (on request)': 0,
                   'Wi-Fi': 0,
                   'Bar': 0,
                   'Spa tub': 0,
                   'In-room internet': 0,
                   'Carbon Monoxide Detector': 0,
                   'Room service': 0,
                   'Internet': 0,
                   'Smoking areas': 0,
                   '24-hour reception': 0,
                   'Currency exchange': 0,
                   'Bridal suite': 0,
                   'Accessibility features': 0,
                   'Concierge services': 0,
                   'Breakfast': 0,
                   'Breakfast in the room': 0,
                   'Snack bar': 0,
                   'Packed Lunches': 0,
                   'Bottled water (at extra charge)': 0,
                   'Car rental': 0,
                   'German': 0,
                   'Portuguese': 0,
                   'Tour assistance': 0,
                   'Library': 0,
                   'Fishing': 0,
                   'Sun Deck': 0,
                   'Free Parking on Premises': 0,
                   'Beach facilities': 0,
                   'Water sport facilities': 0,
                   'Fax and copy machine': 0,
                   'Windsurfing': 0,
                   'Yoga': 0,
                   'Massage': 0,
                   'Babysitting and childcare': 0,
                   'Express check-in/check-out': 0,
                   'Early check-in': 0,
                   'Late check-out': 0,
                   'Private check-in/check-out': 0,
                   'Dryer': 0,
                   'Soundproof rooms': 0,
                   'VIP room amenities': 0,
                   'Bathrobe': 0,
                   'Mosquito net': 0,
                   'Iron': 0,
                   'Free internet': 0,
                   'Russian': 0,
                   "Children's playground": 0,
                   'Temperature control for staff': 0,
                   'Personal protection equipment for staff': 0,
                   'Personal protection equipment for guests': 0,
                   'Next to the beach': 0,
                   'Fire Extinguisher': 0,
                   'No elevators': 0,
                   'Children swimming pool': 0,
                   'Hiking': 0,
                   'Security guard': 0,
                   'Wheelchair Accessible': 0,
                   'First Aid Kit': 0,
                   'Tennis court': 0,
                   'Spa': 0,
                   'Cycling': 0,
                   'Express check-in': 0,
                   'Gift shop': 0,
                   'Locker': 0,
                   'Restaurant (buffet style)': 0,
                   'Bottled water': 0,
                   'Billiards': 0,
                   'Ping-Pong': 0,
                   'Business center': 0,
                   'Event facilities': 0,
                   'Playroom': 0,
                   'Offsite parking reservations required': 0,
                   'ATM': 0,
                   'Airport transportation - drop-off': 0,
                   'Doctor': 0,
                   'Sauna': 0,
                   'Water park': 0,
                   'Newspapers': 0,
                   'Minibar': 0,
                   'Safe (in room)': 0,
                   'Cafe': 0,
                   'Temperature control for guests': 0,
                   'Ticket assistance': 0,
                   'Radio': 0,
                   'Smoking Allowed': 0,
                   'Wake-up service': 0,
                   'Airport transportation - pickup': 0,
                   'No parking': 0,
                   'Gym': 0,
                   'Allergy-free rooms': 0,
                   'Vending machine': 0,
                   'Meeting and presentation facilities': 0,
                   'Shopping on site': 0,
                   'Television in lobby': 0,
                   'Shuttle': 0,
                   'Suitable for Events': 0,
                   'Skiing': 0,
                   'Clothes rack': 0,
                   'Diving': 0,
                   'Indoor Pool': 0,
                   'Mini golf': 0,
                   'Free parking nearby': 0,
                   'Seasonal outdoor swimming pool': 0,
                   'Pool facilities': 0,
                   'Baby sleepers': 0,
                   'Diet menu (on request)': 0,
                   'Photocopy machines': 0,
                   'Korean': 0,
                   'Bike rental': 0,
                   'DVD Player': 0,
                   'Entertainment': 0,
                   'Darts': 0,
                   'Table Tennis': 0,
                   'Breakfast/lunch to go': 0,
                   'Individually packaged food': 0,
                   'Taxi booking': 0,
                   'Arabic': 0,
                   'Wi-Fi in the hotel': 0,
                   'Beauty services': 0,
                   'Solarium': 0,
                   'Bowling': 0,
                   'Casino': 0,
                   'Karaoke': 0,
                   'Nightclub': 0,
                   'Hunt': 0,
                   'Museum': 0,
                   'Water fun': 0,
                   'Badminton': 0,
                   'Horse riding': 0,
                   'Squash': 0,
                   'Boating': 0,
                   'Sailing': 0,
                   'Snorkelling': 0,
                   'Golf course': 0,
                   'Yachting': 0,
                   'Wheelchair access to restaurant': 0,
                   'Adults Only': 0,
                   'Design hotel': 0,
                   'Ski storage': 0,
                   'Ski-to-Door Access': 0,
                   'Ski shuttle': 0,
                   'Ironing accessories (by request)': 0,
                   'Patio': 0,
                   'Shoe shine': 0,
                   'Hammam': 0,
                   'Heated swimming pool': 0,
                   'Baths': 0,
                   'Health club': 0,
                   'Steam room': 0,
                   "Children's menu": 0,
                   'Computer': 0,
                   'Full board rates available': 0,
                   'Free train station shuttle': 0,
                   'Turkish': 0,
                   'Trouser press': 0,
                   'Private beach': 0,
                   'Pets allowed (free)': 0,
                   'Electric car charging': 0,
                   'Express check-out': 0,
                   'Alarm clock': 0,
                   'Chapel': 0,
                   'Polish': 0,
                   'Airport transportation (complimentary)': 0,
                   'Laptop safe': 0,
                   'Buffet breakfast': 0,
                   'Area shuttle': 0,
                   'Japanese': 0,
                   'Free bicycle rental': 0,
                   'Golf сourse (within 3 km)': 0,
                   'Shopping center shuttle': 0,
                   'Pharmacy': 0,
                   'Deposit boxes': 0,
                   'Beach shuttle': 0,
                   'Poolside bar': 0,
                   'Outdoor heated swimming pool': 0,
                   'Fax machine': 0,
                   'Rooftop pool': 0,
                   'Pets allowed (under 5 kg)': 0,
                   'Ice skating': 0,
                   'Kids club': 0,
                   'Winery': 0,
                   'Transfer to the beach': 0,
                   'Smoking allowed in bedrooms': 0,
                   'Mini-fridge': 0,
                   'Ski passes available': 0,
                   'Doorman': 0,
                   'Doctor on call': 0,
                   'Pets allowed (under 5 kg) (surcharge)': 0,
                   'Snowmobile and quad bikes rental': 0,
                   'Ski facilities rental': 0,
                   'Snowboard': 0,
                   'Skiing Off-site': 0,
                   'Music system': 0,
                   'Free shuttle': 0,
                   'Wheelchair access to bar': 0,
                   'Rental video equipment and computers': 0}
    else:
        hotel_w = {'distances': 5,
                   'price_with_all_taxes': 3,
                   'is_meal': 3,
                   'free_cancellation_parameter': 0,
                   'star_rating': 10,
                   'rooms_number': 0,
                   'latitude': 0,
                   'longitude': 0,
                   'no_of_images': 1,
                   'total_rating': 3,
                   'cleanness_rating': 0,
                   'room_rating': 0,
                   'services_rating': 0,
                   'meal_rating': 0,
                   'hygiene_rating': 0,
                   'wifi_rating': 0,
                   'price_rating': 0,
                   'location_rating': 0,
                   'Washing machine': 0,
                   'Dishwasher': 0,
                   'Fridge': 0,
                   'TV': 0,
                   'Hairdryer': 0,
                   'Iron and board': 0,
                   'Coffee/tea for guests': 0,
                   'Kitchen': 0,
                   'Microwave oven': 0,
                   'Free Wi-Fi': 0,
                   'Internet access': 0,
                   'Air conditioning': 0,
                   'Heating': 0,
                   'Garden': 0,
                   'Terrace': 0,
                   'Indoor Fireplace': 0,
                   'Shower/Bathtub': 0,
                   'Shower': 0,
                   'Barbecue grill(s)': 0,
                   'Parking': 0,
                   'Parking nearby': 0,
                   'Swimming pool': 0,
                   'Outdoor pool': 0,
                   'Pets allowed': 0,
                   'Elevator/lift': 0,
                   'Smoke-free property': 0,
                   'All Spaces Non-Smoking (public and private)': 0,
                   'Upper floors accessible by elevator': 0,
                   'Non-smoking rooms': 0,
                   'Interconnecting rooms available': 0,
                   'Family room': 0,
                   'Cable TV': 0,
                   'Flat-screen TV': 0,
                   'Wardrobe/Closet': 0,
                   'Linens': 0,
                   'Toiletries': 0,
                   'Ironing': 0,
                   'Laundry': 0,
                   'Dry-cleaning': 0,
                   'Coffeemaker': 0,
                   'Airport transportation': 0,
                   'Spanish': 0,
                   'English': 0,
                   'Italian': 0,
                   'French': 0,
                   'Garage': 0,
                   'Beach/pool towels': 0,
                   'Family/Kid Friendly': 0,
                   "Kids' TV Networks": 0,
                   'Pets Not Allowed': 0,
                   'Outdoor furniture': 0,
                   'Multi-language staff': 0,
                   'Free parking': 0,
                   'Fitness facilities': 0,
                   'Extra decontamination measures': 0,
                   'Contactless check-in and/or check-out': 0,
                   'Additional measures against COVID-19': 0,
                   'Reception desk': 0,
                   'Slippers': 0,
                   'Telephone': 0,
                   'Restaurant': 0,
                   'Kettle': 0,
                   'Safe-deposit box': 0,
                   'Luggage storage': 0,
                   'Transfer services': 0,
                   'Smoke Detector': 0,
                   'Kitchenette': 0,
                   'Bathtub': 0,
                   'Common kitchen': 0,
                   'Chinese': 0,
                   'Conference Hall': 0,
                   'Picnic area': 0,
                   'Barbeque': 0,
                   'Hairdryer (on request)': 0,
                   'Wi-Fi': 0,
                   'Bar': 0,
                   'Spa tub': 0,
                   'In-room internet': 0,
                   'Carbon Monoxide Detector': 0,
                   'Room service': 0,
                   'Internet': 0,
                   'Smoking areas': 0,
                   '24-hour reception': 0,
                   'Currency exchange': 0,
                   'Bridal suite': 0,
                   'Accessibility features': 0,
                   'Concierge services': 0,
                   'Breakfast': 0,
                   'Breakfast in the room': 0,
                   'Snack bar': 0,
                   'Packed Lunches': 0,
                   'Bottled water (at extra charge)': 0,
                   'Car rental': 0,
                   'German': 0,
                   'Portuguese': 0,
                   'Tour assistance': 0,
                   'Library': 0,
                   'Fishing': 0,
                   'Sun Deck': 0,
                   'Free Parking on Premises': 0,
                   'Beach facilities': 0,
                   'Water sport facilities': 0,
                   'Fax and copy machine': 0,
                   'Windsurfing': 0,
                   'Yoga': 0,
                   'Massage': 0,
                   'Babysitting and childcare': 0,
                   'Express check-in/check-out': 0,
                   'Early check-in': 0,
                   'Late check-out': 0,
                   'Private check-in/check-out': 0,
                   'Dryer': 0,
                   'Soundproof rooms': 0,
                   'VIP room amenities': 0,
                   'Bathrobe': 0,
                   'Mosquito net': 0,
                   'Iron': 0,
                   'Free internet': 0,
                   'Russian': 0,
                   "Children's playground": 0,
                   'Temperature control for staff': 0,
                   'Personal protection equipment for staff': 0,
                   'Personal protection equipment for guests': 0,
                   'Next to the beach': 0,
                   'Fire Extinguisher': 0,
                   'No elevators': 0,
                   'Children swimming pool': 0,
                   'Hiking': 0,
                   'Security guard': 0,
                   'Wheelchair Accessible': 0,
                   'First Aid Kit': 0,
                   'Tennis court': 0,
                   'Spa': 0,
                   'Cycling': 0,
                   'Express check-in': 0,
                   'Gift shop': 0,
                   'Locker': 0,
                   'Restaurant (buffet style)': 0,
                   'Bottled water': 0,
                   'Billiards': 0,
                   'Ping-Pong': 0,
                   'Business center': 0,
                   'Event facilities': 0,
                   'Playroom': 0,
                   'Offsite parking reservations required': 0,
                   'ATM': 0,
                   'Airport transportation - drop-off': 0,
                   'Doctor': 0,
                   'Sauna': 0,
                   'Water park': 0,
                   'Newspapers': 0,
                   'Minibar': 0,
                   'Safe (in room)': 0,
                   'Cafe': 0,
                   'Temperature control for guests': 0,
                   'Ticket assistance': 0,
                   'Radio': 0,
                   'Smoking Allowed': 0,
                   'Wake-up service': 0,
                   'Airport transportation - pickup': 0,
                   'No parking': 0,
                   'Gym': 0,
                   'Allergy-free rooms': 0,
                   'Vending machine': 0,
                   'Meeting and presentation facilities': 0,
                   'Shopping on site': 0,
                   'Television in lobby': 0,
                   'Shuttle': 0,
                   'Suitable for Events': 0,
                   'Skiing': 0,
                   'Clothes rack': 0,
                   'Diving': 0,
                   'Indoor Pool': 0,
                   'Mini golf': 0,
                   'Free parking nearby': 0,
                   'Seasonal outdoor swimming pool': 0,
                   'Pool facilities': 0,
                   'Baby sleepers': 0,
                   'Diet menu (on request)': 0,
                   'Photocopy machines': 0,
                   'Korean': 0,
                   'Bike rental': 0,
                   'DVD Player': 0,
                   'Entertainment': 0,
                   'Darts': 0,
                   'Table Tennis': 0,
                   'Breakfast/lunch to go': 0,
                   'Individually packaged food': 0,
                   'Taxi booking': 0,
                   'Arabic': 0,
                   'Wi-Fi in the hotel': 0,
                   'Beauty services': 0,
                   'Solarium': 0,
                   'Bowling': 0,
                   'Casino': 0,
                   'Karaoke': 0,
                   'Nightclub': 0,
                   'Hunt': 0,
                   'Museum': 0,
                   'Water fun': 0,
                   'Badminton': 0,
                   'Horse riding': 0,
                   'Squash': 0,
                   'Boating': 0,
                   'Sailing': 0,
                   'Snorkelling': 0,
                   'Golf course': 0,
                   'Yachting': 0,
                   'Wheelchair access to restaurant': 0,
                   'Adults Only': 0,
                   'Design hotel': 0,
                   'Ski storage': 0,
                   'Ski-to-Door Access': 0,
                   'Ski shuttle': 0,
                   'Ironing accessories (by request)': 0,
                   'Patio': 0,
                   'Shoe shine': 0,
                   'Hammam': 0,
                   'Heated swimming pool': 0,
                   'Baths': 0,
                   'Health club': 0,
                   'Steam room': 0,
                   "Children's menu": 0,
                   'Computer': 0,
                   'Full board rates available': 0,
                   'Free train station shuttle': 0,
                   'Turkish': 0,
                   'Trouser press': 0,
                   'Private beach': 0,
                   'Pets allowed (free)': 0,
                   'Electric car charging': 0,
                   'Express check-out': 0,
                   'Alarm clock': 0,
                   'Chapel': 0,
                   'Polish': 0,
                   'Airport transportation (complimentary)': 0,
                   'Laptop safe': 0,
                   'Buffet breakfast': 0,
                   'Area shuttle': 0,
                   'Japanese': 0,
                   'Free bicycle rental': 0,
                   'Golf сourse (within 3 km)': 0,
                   'Shopping center shuttle': 0,
                   'Pharmacy': 0,
                   'Deposit boxes': 0,
                   'Beach shuttle': 0,
                   'Poolside bar': 0,
                   'Outdoor heated swimming pool': 0,
                   'Fax machine': 0,
                   'Rooftop pool': 0,
                   'Pets allowed (under 5 kg)': 0,
                   'Ice skating': 0,
                   'Kids club': 0,
                   'Winery': 0,
                   'Transfer to the beach': 0,
                   'Smoking allowed in bedrooms': 0,
                   'Mini-fridge': 0,
                   'Ski passes available': 0,
                   'Doorman': 0,
                   'Doctor on call': 0,
                   'Pets allowed (under 5 kg) (surcharge)': 0,
                   'Snowmobile and quad bikes rental': 0,
                   'Ski facilities rental': 0,
                   'Snowboard': 0,
                   'Skiing Off-site': 0,
                   'Music system': 0,
                   'Free shuttle': 0,
                   'Wheelchair access to bar': 0,
                   'Rental video equipment and computers': 0}
    return hotel_w


def location_radius(activity_tag, days_to_stay, picked_budget):
    if activity_tag == 'urban_exploration' and days_to_stay < 5 and picked_budget == 'Standard':
        radius = 3000
    else:
        radius = 5000
    return radius
