"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.
"""
import os
from pathlib import Path
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv()

# Environment variables
protocol = os.getenv('PROTOCOL')
url = os.getenv('URL')
react_port = os.getenv('REACT_PORT')
django_port = os.getenv('DJANGO_PORT')
redis_port = os.getenv('REDIS_PORT')
localhost = '127.0.0.1'
WORKMODE = os.getenv('VITE_WORKMODE', 'prod')  # Default to production


BACKEND_URL = f'{protocol}://{url}:{django_port}'

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-=tipn%0ut^gk7i-oo1lbv$16zyb!8oe48r$5(xx-m5^mt4e!z%'
DEBUG = False

if WORKMODE == "dev":
    ALLOWED_HOSTS = ['*']  # Allow all hosts in dev
else:
    ALLOWED_HOSTS = [url, 'localhost', '127.0.0.1', '192.168.1.9', 'picotrip.com', 'www.picotrip.com']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- CORS configuration based on WORKMODE ---
if WORKMODE == "dev":
    # Development: allow all origins
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_HEADERS = list(default_headers) + ["sessionid", "cache-control"]
    CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
else:
    # Production: restrict origins
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        f"{protocol}://{url}:{react_port}",
        f"http://localhost:{react_port}",
        "https://picotrip.com",
        "https://www.picotrip.com",
        "http://127.0.0.1:3000",
    ]
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_HEADERS = list(default_headers) + ["sessionid", "cache-control"]
    CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login redirects
LOGIN_REDIRECT_URL = "create"
LOGOUT_REDIRECT_URL = "home"

# Channels
CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer",},
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{asctime} {levelname} [{name}] {message}', 'style': '{', 'datefmt': '%Y-%m-%d %H:%M:%S'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'level': 'INFO', 'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': 'django_debug.log', 'formatter': 'verbose'},
    },
    'loggers': {'root': {'handlers': ['console', 'file'], 'level': 'INFO'}},
}

# Redis session backend
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{localhost}:{redis_port}/1',
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'}
    }
}

# Celery
CELERY_BROKER_URL = f'redis://{localhost}:{redis_port}/0'
CELERY_RESULT_BACKEND = f'redis://{localhost}:{redis_port}/0'

# Cookies configuration
if protocol == 'http':
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
