llc_list = {
    "FR": "Ryanair",
    "U2": "easyJet",
    "W6": "Wizz Air",
    "VY": "Vueling Airlines",
    "F9": "Frontier Airlines",
    "NK": "Spirit Airlines",
    "G8": "GoAir",
    "AK": "AirAsia",
    "TR": "Scoot",
    "J9": "Jazeera Airways",
    "3O": "Air Arabia Maroc",
    "6E": "IndiGo",
    "JQ": "Jetstar Airways",
    "DG": "Cebgo",
    "VJ": "VietJet Air",
    "PC": "Pegasus Airlines",
    "QV": "Lao Airlines",
    "SC": "Shandong Airlines",
    "FD": "Thai AirAsia",
    "QG": "Citilink",
    "XY": "flynas",
    "ZL": "Rex Airlines",
    "VB": "VivaAerobus",
    "5J": "Cebu Pacific",
    "HM": "Air Seychelles",
    "ZI": "Aigle Azur",
    "QZ": "Indonesia AirAsia",
    "BL": "Bamboo Airways",
    "JZ": "Jambojet",
    "X3": "TUI fly",
    "J7": "Afrijet Business Service",
    "IJ": "Spring Airlines Japan",
    "2P": "PAL Express",
    "FD": "Thai AirAsia",
    "JW": "Vanilla Air",
    "TT": "Tigerair Australia",
    "TO": "Transavia France",
    "HV": "Transavia",
    "D7": "AirAsia X",
    "XT": "Indonesia AirAsia X",
    "5P": "Small Planet Airlines",
    "IJ": "Spring Airlines Japan",
    "SL": "Thai Lion Air",
    "OD": "Malindo Air",
    "DP": "Pobeda",
    "DV": "SCAT Airlines",
    "PE": "People's Viennaline",
    "HO": "Juneyao Airlines",
    "8P": "Pacific Coastal Airlines",
    "9C": "Spring Airlines",
    "Z2": "Philippines AirAsia",
    "SN": "Brussels Airlines (low-cost subsidiary)",
    "MH": "Malaysia Airlines (Firefly low-cost subsidiary)",
    "XN": "FlyBondi",
    "OG": "Go First (formerly GoAir)",
    "G9": "Air Arabia",
    "PF": "Primera Air",
    "T4": "Trip Linhas Aéreas",
    "LS": "Jet2",
    "IJ": "Spring Japan",
    "XQ": "SunExpress",
    "K6": "Cambodia Angkor Air",
    "XY": "flynas",
    "R3": "Yakutia Airlines",
    "WE": "Thai Smile",
    "SG": "SpiceJet",
    "TT": "Tigerair",
    "8Q": "Onur Air",
    "AD": "Azul Brazilian Airlines",
    "AV": "Avianca",
    "EI": "Aer Lingus",
    "HA": "Hawaiian Airlines",
    "MM": "Peach Aviation",
    "PR": "Philippine Airlines",
    "RX": "Regent Airways",
    "XJ": "Thai AirAsia X",
    "LJ": "Jin Air",
    "IH": "Southern Airways Express",
}

