import os
import pandas as pd

# Get the current directory
current_directory = os.path.dirname(__file__)
# Construct the path to the parquet file
main_databse_path = os.path.join(current_directory, 'indexed_data')
airports_coordinates_path = os.path.join(current_directory, 'airport_coordinates.parquet')
skiing_database_path = os.path.join(current_directory, 'ski_resorts.parquet')

# Read the parquet file
main_database = pd.read_parquet(main_databse_path, engine='pyarrow').astype('object')
airport_coordinates = pd.read_parquet(airports_coordinates_path, engine='pyarrow')
skiing_database = pd.read_parquet(skiing_database_path, engine='pyarrow')

country_names = {
    'AF': 'Afghanistan',
    'AX': 'Åland Islands',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AS': 'American Samoa',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AI': 'Anguilla',
    'AQ': 'Antarctica',
    'AG': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AW': 'Aruba',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BM': 'Bermuda',
    'BT': 'Bhutan',
    'BO': 'Bolivia (Plurinational State of)',
    'BQ': 'Bonaire, Sint Eustatius and Saba',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'IO': 'British Indian Ocean Territory',
    'BN': 'Brunei Darussalam',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cabo Verde',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'KY': 'Cayman Islands',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CX': 'Christmas Island',
    'CC': 'Cocos (Keeling) Islands',
    'CO': 'Colombia',
    'KM': 'Comoros',
    'CG': 'Congo',
    'CD': 'Congo (Democratic Republic of the)',
    'CK': 'Cook Islands',
    'CR': 'Costa Rica',
    'CI': "Côte d'Ivoire",
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CW': 'Curaçao',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'ET': 'Ethiopia',
    'FK': 'Falkland Islands (Malvinas)',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GF': 'French Guiana',
    'PF': 'French Polynesia',
    'TF': 'French Southern Territories',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GD': 'Grenada',
    'GP': 'Guadeloupe',
    'GU': 'Guam',
    'GT': 'Guatemala',
    'GG': 'Guernsey',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HM': 'Heard Island and McDonald Islands',
    'VA': 'Holy See',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran (Islamic Republic of)',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IM': 'Isle of Man',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JE': 'Jersey',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KP': "Korea (Democratic People's Republic of)",
    'KR': 'Korea (Republic of)',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': "Lao People's Democratic Republic",
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MO': 'Macao',
    'MK': 'Macedonia (the former Yugoslav Republic of)',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'YT': 'Mayotte',
    'MX': 'Mexico',
    'FM': 'Micronesia (Federated States of)',
    'MD': 'Moldova (Republic of)',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MS': 'Montserrat',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NU': 'Niue',
    'NF': 'Norfolk Island',
    'MP': 'Northern Mariana Islands',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestine, State of',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PN': 'Pitcairn',
    'PL': 'Poland',
    'PT': 'Portugal',
    'PR': 'Puerto Rico',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'BL': 'Saint Barthélemy',
    'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    'KN': 'Saint Kitts and Nevis',
    'LC': 'Saint Lucia',
    'MF': 'Saint Martin (French part)',
    'PM': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and the Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'ST': 'Sao Tome and Principe',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SX': 'Sint Maarten (Dutch part)',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'GS': 'South Georgia and the South Sandwich Islands',
    'SS': 'South Sudan',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SJ': 'Svalbard and Jan Mayen',
    'SZ': 'Swaziland',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syrian Arab Republic',
    'TW': 'Taiwan, Province of China',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TK': 'Tokelau',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'TM': 'Turkmenistan',
    'TC': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'US': 'USA',
    'UM': 'United States Minor Outlying Islands',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela',
    'VN': 'Viet Nam',
    'VG': 'Virgin Islands (British)',
    'VI': 'Virgin Islands (U.S.)',
    'WF': 'Wallis and Futuna',
    'EH': 'Western Sahara',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
}

amenities = {'Washing machine': 0,
             'Dishwasher': 0,
             'Fridge': 0,
             'TV': 0,
             'Hairdryer': 0,
             'Iron and board': 0,
             'Coffee/tea for guests': 0,
             'Kitchen': 0,
             'Microwave oven': 0,
             'Free Wi-Fi': 0,
             'Internet access': 0,
             'Air conditioning': 0,
             'Heating': 0,
             'Garden': 0,
             'Terrace': 0,
             'Indoor Fireplace': 0,
             'Shower/Bathtub': 0,
             'Shower': 0,
             'Barbecue grill(s)': 0,
             'Parking': 0,
             'Parking nearby': 0,
             'Swimming pool': 0,
             'Outdoor pool': 0,
             'Pets allowed': 0,
             'Elevator/lift': 0,
             'Smoke-free property': 0,
             'All Spaces Non-Smoking (public and private)': 0,
             'Upper floors accessible by elevator': 0,
             'Non-smoking rooms': 0,
             'Interconnecting rooms available': 0,
             'Family room': 0,
             'Cable TV': 0,
             'Flat-screen TV': 0,
             'Wardrobe/Closet': 0,
             'Linens': 0,
             'Toiletries': 0,
             'Ironing': 0,
             'Laundry': 0,
             'Dry-cleaning': 0,
             'Coffeemaker': 0,
             'Airport transportation': 0,
             'Spanish': 0,
             'English': 0,
             'Italian': 0,
             'French': 0,
             'Garage': 0,
             'Beach/pool towels': 0,
             'Family/Kid Friendly': 0,
             "Kids' TV Networks": 0,
             'Pets Not Allowed': 0,
             'Outdoor furniture': 0,
             'Multi-language staff': 0,
             'Free parking': 0,
             'Fitness facilities': 0,
             'Extra decontamination measures': 0,
             'Contactless check-in and/or check-out': 0,
             'Additional measures against COVID-19': 0,
             'Reception desk': 0,
             'Slippers': 0,
             'Telephone': 0,
             'Restaurant': 0,
             'Kettle': 0,
             'Safe-deposit box': 0,
             'Luggage storage': 0,
             'Transfer services': 0,
             'Smoke Detector': 0,
             'Kitchenette': 0,
             'Bathtub': 0,
             'Common kitchen': 0,
             'Chinese': 0,
             'Conference Hall': 0,
             'Picnic area': 0,
             'Barbeque': 0,
             'Hairdryer (on request)': 0,
             'Wi-Fi': 0,
             'Bar': 0,
             'Spa tub': 0,
             'In-room internet': 0,
             'Carbon Monoxide Detector': 0,
             'Room service': 0,
             'Internet': 0,
             'Smoking areas': 0,
             '24-hour reception': 0,
             'Currency exchange': 0,
             'Bridal suite': 0,
             'Accessibility features': 0,
             'Concierge services': 0,
             'Breakfast': 0,
             'Breakfast in the room': 0,
             'Snack bar': 0,
             'Packed Lunches': 0,
             'Bottled water (at extra charge)': 0,
             'Car rental': 0,
             'German': 0,
             'Portuguese': 0,
             'Tour assistance': 0,
             'Library': 0,
             'Fishing': 0,
             'Sun Deck': 0,
             'Free Parking on Premises': 0,
             'Beach facilities': 0,
             'Water sport facilities': 0,
             'Fax and copy machine': 0,
             'Windsurfing': 0,
             'Yoga': 0,
             'Massage': 0,
             'Babysitting and childcare': 0,
             'Express check-in/check-out': 0,
             'Early check-in': 0,
             'Late check-out': 0,
             'Private check-in/check-out': 0,
             'Dryer': 0,
             'Soundproof rooms': 0,
             'VIP room amenities': 0,
             'Bathrobe': 0,
             'Mosquito net': 0,
             'Iron': 0,
             'Free internet': 0,
             'Russian': 0,
             "Children's playground": 0,
             'Temperature control for staff': 0,
             'Personal protection equipment for staff': 0,
             'Personal protection equipment for guests': 0,
             'Next to the beach': 0,
             'Fire Extinguisher': 0,
             'No elevators': 0,
             'Children swimming pool': 0,
             'Hiking': 0,
             'Security guard': 0,
             'Wheelchair Accessible': 0,
             'First Aid Kit': 0,
             'Tennis court': 0,
             'Spa': 0,
             'Cycling': 0,
             'Express check-in': 0,
             'Gift shop': 0,
             'Locker': 0,
             'Restaurant (buffet style)': 0,
             'Bottled water': 0,
             'Billiards': 0,
             'Ping-Pong': 0,
             'Business center': 0,
             'Event facilities': 0,
             'Playroom': 0,
             'Offsite parking reservations required': 0,
             'ATM': 0,
             'Airport transportation - drop-off': 0,
             'Doctor': 0,
             'Sauna': 0,
             'Water park': 0,
             'Newspapers': 0,
             'Minibar': 0,
             'Safe (in room)': 0,
             'Cafe': 0,
             'Temperature control for guests': 0,
             'Ticket assistance': 0,
             'Radio': 0,
             'Smoking Allowed': 0,
             'Wake-up service': 0,
             'Airport transportation - pickup': 0,
             'No parking': 0,
             'Gym': 0,
             'Allergy-free rooms': 0,
             'Vending machine': 0,
             'Meeting and presentation facilities': 0,
             'Shopping on site': 0,
             'Television in lobby': 0,
             'Shuttle': 0,
             'Suitable for Events': 0,
             'Skiing': 0,
             'Clothes rack': 0,
             'Diving': 0,
             'Indoor Pool': 0,
             'Mini golf': 0,
             'Free parking nearby': 0,
             'Seasonal outdoor swimming pool': 0,
             'Pool facilities': 0,
             'Baby sleepers': 0,
             'Diet menu (on request)': 0,
             'Photocopy machines': 0,
             'Korean': 0,
             'Bike rental': 0,
             'DVD Player': 0,
             'Entertainment': 0,
             'Darts': 0,
             'Table Tennis': 0,
             'Breakfast/lunch to go': 0,
             'Individually packaged food': 0,
             'Taxi booking': 0,
             'Arabic': 0,
             'Wi-Fi in the hotel': 0,
             'Beauty services': 0,
             'Solarium': 0,
             'Bowling': 0,
             'Casino': 0,
             'Karaoke': 0,
             'Nightclub': 0,
             'Hunt': 0,
             'Museum': 0,
             'Water fun': 0,
             'Badminton': 0,
             'Horse riding': 0,
             'Squash': 0,
             'Boating': 0,
             'Sailing': 0,
             'Snorkelling': 0,
             'Golf course': 0,
             'Yachting': 0,
             'Wheelchair access to restaurant': 0,
             'Adults Only': 0,
             'Design hotel': 0,
             'Ski storage': 0,
             'Ski-to-Door Access': 0,
             'Ski shuttle': 0,
             'Ironing accessories (by request)': 0,
             'Patio': 0,
             'Shoe shine': 0,
             'Hammam': 0,
             'Heated swimming pool': 0,
             'Baths': 0,
             'Health club': 0,
             'Steam room': 0,
             "Children's menu": 0,
             'Computer': 0,
             'Full board rates available': 0,
             'Free train station shuttle': 0,
             'Turkish': 0,
             'Trouser press': 0,
             'Private beach': 0,
             'Pets allowed (free)': 0,
             'Electric car charging': 0,
             'Express check-out': 0,
             'Alarm clock': 0,
             'Chapel': 0,
             'Polish': 0,
             'Airport transportation (complimentary)': 0,
             'Laptop safe': 0,
             'Buffet breakfast': 0,
             'Area shuttle': 0,
             'Japanese': 0,
             'Free bicycle rental': 0,
             'Golf сourse (within 3 km)': 0,
             'Shopping center shuttle': 0,
             'Pharmacy': 0,
             'Deposit boxes': 0,
             'Beach shuttle': 0,
             'Poolside bar': 0,
             'Outdoor heated swimming pool': 0,
             'Fax machine': 0,
             'Rooftop pool': 0,
             'Pets allowed (under 5 kg)': 0,
             'Ice skating': 0,
             'Kids club': 0,
             'Winery': 0,
             'Transfer to the beach': 0,
             'Smoking allowed in bedrooms': 0,
             'Mini-fridge': 0,
             'Ski passes available': 0,
             'Doorman': 0,
             'Doctor on call': 0,
             'Pets allowed (under 5 kg) (surcharge)': 0,
             'Snowmobile and quad bikes rental': 0,
             'Ski facilities rental': 0,
             'Snowboard': 0,
             'Skiing Off-site': 0,
             'Music system': 0}

hotels_parameters_list = ['is_meal',
                          'price_with_all_taxes',
                          'free_cancellation_parameter',
                          'indexes',
                          'kind',
                          'star_rating',
                          'rooms_number',
                          'no_of_images',
                          'total_rating',
                          'cleanness_rating',
                          'room_rating',
                          'services_rating',
                          'meal_rating',
                          'hygiene_rating',
                          'wifi_rating',
                          'price_rating',
                          'location_rating',
                          'Washing machine',
                          'Dishwasher',
                          'Fridge',
                          'TV',
                          'Hairdryer',
                          'Iron and board',
                          'Coffee/tea for guests',
                          'Kitchen',
                          'Microwave oven',
                          'Free Wi-Fi',
                          'Internet access',
                          'Air conditioning',
                          'Heating',
                          'Garden',
                          'Terrace',
                          'Indoor Fireplace',
                          'Shower/Bathtub',
                          'Shower',
                          'Barbecue grill(s)',
                          'Parking',
                          'Parking nearby',
                          'Swimming pool',
                          'Outdoor pool',
                          'Pets allowed',
                          'Elevator/lift',
                          'Smoke-free property',
                          'All Spaces Non-Smoking (public and private)',
                          'Upper floors accessible by elevator',
                          'Non-smoking rooms',
                          'Interconnecting rooms available',
                          'Family room',
                          'Cable TV',
                          'Flat-screen TV',
                          'Wardrobe/Closet',
                          'Linens',
                          'Toiletries',
                          'Ironing',
                          'Laundry',
                          'Dry-cleaning',
                          'Coffeemaker',
                          'Airport transportation',
                          'Spanish',
                          'English',
                          'Italian',
                          'French',
                          'Garage',
                          'Beach/pool towels',
                          'Family/Kid Friendly',
                          "Kids' TV Networks",
                          'Pets Not Allowed',
                          'Outdoor furniture',
                          'Multi-language staff',
                          'Free parking',
                          'Fitness facilities',
                          'Extra decontamination measures',
                          'Contactless check-in and/or check-out',
                          'Additional measures against COVID-19',
                          'Reception desk',
                          'Slippers',
                          'Telephone',
                          'Restaurant',
                          'Kettle',
                          'Safe-deposit box',
                          'Luggage storage',
                          'Transfer services',
                          'Smoke Detector',
                          'Kitchenette',
                          'Bathtub',
                          'Common kitchen',
                          'Chinese',
                          'Conference Hall',
                          'Picnic area',
                          'Barbeque',
                          'Hairdryer (on request)',
                          'Wi-Fi',
                          'Bar',
                          'Spa tub',
                          'In-room internet',
                          'Carbon Monoxide Detector',
                          'Room service',
                          'Internet',
                          'Smoking areas',
                          '24-hour reception',
                          'Currency exchange',
                          'Bridal suite',
                          'Accessibility features',
                          'Concierge services',
                          'Breakfast',
                          'Breakfast in the room',
                          'Snack bar',
                          'Packed Lunches',
                          'Bottled water (at extra charge)',
                          'Car rental',
                          'German',
                          'Portuguese',
                          'Tour assistance',
                          'Library',
                          'Fishing',
                          'Sun Deck',
                          'Free Parking on Premises',
                          'Beach facilities',
                          'Water sport facilities',
                          'Fax and copy machine',
                          'Windsurfing',
                          'Yoga',
                          'Massage',
                          'Babysitting and childcare',
                          'Express check-in/check-out',
                          'Early check-in',
                          'Late check-out',
                          'Private check-in/check-out',
                          'Dryer',
                          'Soundproof rooms',
                          'VIP room amenities',
                          'Bathrobe',
                          'Mosquito net',
                          'Iron',
                          'Free internet',
                          'Russian',
                          "Children's playground",
                          'Temperature control for staff',
                          'Personal protection equipment for staff',
                          'Personal protection equipment for guests',
                          'Next to the beach',
                          'Fire Extinguisher',
                          'No elevators',
                          'Children swimming pool',
                          'Hiking',
                          'Security guard',
                          'Wheelchair Accessible',
                          'First Aid Kit',
                          'Tennis court',
                          'Spa',
                          'Cycling',
                          'Express check-in',
                          'Gift shop',
                          'Locker',
                          'Restaurant (buffet style)',
                          'Bottled water',
                          'Billiards',
                          'Ping-Pong',
                          'Business center',
                          'Event facilities',
                          'Playroom',
                          'Offsite parking reservations required',
                          'ATM',
                          'Airport transportation - drop-off',
                          'Doctor',
                          'Sauna',
                          'Water park',
                          'Newspapers',
                          'Minibar',
                          'Safe (in room)',
                          'Cafe',
                          'Temperature control for guests',
                          'Ticket assistance',
                          'Radio',
                          'Smoking Allowed',
                          'Wake-up service',
                          'Airport transportation - pickup',
                          'No parking',
                          'Gym',
                          'Allergy-free rooms',
                          'Vending machine',
                          'Meeting and presentation facilities',
                          'Shopping on site',
                          'Television in lobby',
                          'Shuttle',
                          'Suitable for Events',
                          'Skiing',
                          'Clothes rack',
                          'Diving',
                          'Indoor Pool',
                          'Mini golf',
                          'Free parking nearby',
                          'Seasonal outdoor swimming pool',
                          'Pool facilities',
                          'Baby sleepers',
                          'Diet menu (on request)',
                          'Photocopy machines',
                          'Korean',
                          'Bike rental',
                          'DVD Player',
                          'Entertainment',
                          'Darts',
                          'Table Tennis',
                          'Breakfast/lunch to go',
                          'Individually packaged food',
                          'Taxi booking',
                          'Arabic',
                          'Wi-Fi in the hotel',
                          'Beauty services',
                          'Solarium',
                          'Bowling',
                          'Casino',
                          'Karaoke',
                          'Nightclub',
                          'Hunt',
                          'Museum',
                          'Water fun',
                          'Badminton',
                          'Horse riding',
                          'Squash',
                          'Boating',
                          'Sailing',
                          'Snorkelling',
                          'Golf course',
                          'Yachting',
                          'Wheelchair access to restaurant',
                          'Adults Only',
                          'Design hotel',
                          'Ski storage',
                          'Ski-to-Door Access',
                          'Ski shuttle',
                          'Ironing accessories (by request)',
                          'Patio',
                          'Shoe shine',
                          'Hammam',
                          'Heated swimming pool',
                          'Baths',
                          'Health club',
                          'Steam room',
                          "Children's menu",
                          'Computer',
                          'Full board rates available',
                          'Free train station shuttle',
                          'Turkish',
                          'Trouser press',
                          'Private beach',
                          'Pets allowed (free)',
                          'Electric car charging',
                          'Express check-out',
                          'Alarm clock',
                          'Chapel',
                          'Polish',
                          'Airport transportation (complimentary)',
                          'Laptop safe',
                          'Buffet breakfast',
                          'Area shuttle',
                          'Japanese',
                          'Free bicycle rental',
                          'Golf сourse (within 3 km)',
                          'Shopping center shuttle',
                          'Pharmacy',
                          'Deposit boxes',
                          'Beach shuttle',
                          'Poolside bar',
                          'Outdoor heated swimming pool',
                          'Fax machine',
                          'Rooftop pool',
                          'Pets allowed (under 5 kg)',
                          'Ice skating',
                          'Kids club',
                          'Winery',
                          'Transfer to the beach',
                          'Smoking allowed in bedrooms',
                          'Mini-fridge',
                          'Ski passes available',
                          'Doorman',
                          'Doctor on call',
                          'Pets allowed (under 5 kg) (surcharge)',
                          'Snowmobile and quad bikes rental',
                          'Ski facilities rental',
                          'Snowboard',
                          'Skiing Off-site',
                          'Music system',
                          'Wheelchair access to bar',
                          'Rental video equipment and computers',
                          'Free shuttle',
                          'distance_from_city_center']
