# Generated by Django 5.0.4 on 2024-04-25 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_usersearch_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='activity_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
