# Generated by Django 5.0.4 on 2024-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_usersearch_activity_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='picked_cities',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersearch',
            name='picked_countries',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
